import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver=webdriver.Chrome()
driver.maximize_window()

driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
time.sleep(2)

driver.find_element(By.XPATH,"//a[normalize-space()='OrangeHRM, Inc']").click()
time.sleep(5)

#window ids--generated by the browser

# winid=driver.current_window_handle # it will give the window id of single/current window where driver instnace is pointing
# print("The window id is ", winid) #478DB745DB64FF31726E19E60DF965B2,2F2240393B123119E496D24D848DFA5C

# get the window id for multiple window

winids=driver.window_handles  # collection---list-- bcoz duplicates are not allowed
print(winids)
# print(type(winids))


#Approach-1
#
# parentid=winids[0]
# childid=winids[1]
#
# print(parentid,childid)
#
# driver.switch_to.window(childid)
#
# text1=driver.find_element(By.XPATH,'//*[@id="navbarSupportedContent"]/div[2]/ul/li[2]/a/button').text
# print(text1) #Contact Sales
# time.sleep(5)
# print(driver.title) #Human Resources Management Software | OrangeHRM

#Approach-2

# for win in winids:
#     driver.switch_to.window(win)
#     print(driver.title)


# for win in winids:
#     driver.switch_to.window(win)
#     if driver.title=="Human Resources Management Software | OrangeHRM":
#         driver.close()

